// Complete player attribute data for the Mystery Player guessing game
// All heights format: "6'3\"" | Ages as of 2025 season

export interface NBAAttrs { height: string; jersey: number; team: string; position: string; conference: string; college: string; age: number }
export interface NFLAttrs { height: string; jersey: number; team: string; position: string; conference: string; college: string; age: number }
export interface MLBAttrs { bat: string; throwing: string; country: string; team: string; position: string; division: string; age: number }
export interface NHLAttrs { height: string; jersey: number; team: string; position: string; conference: string; country: string; age: number }
export type PlayerAttrs = NBAAttrs | NFLAttrs | MLBAttrs | NHLAttrs;

export const NBA_ATTRS: Record<string, NBAAttrs> = {
  "LeBron James":            { height: "6'9\"",  jersey: 23,  team: "LAL", position: "SF", conference: "Western", college: "None (HS)",          age: 40 },
  "Stephen Curry":           { height: "6'2\"",  jersey: 30,  team: "GSW", position: "PG", conference: "Western", college: "Davidson",            age: 37 },
  "Kevin Durant":            { height: "6'10\"", jersey: 35,  team: "PHX", position: "SF", conference: "Western", college: "Texas",               age: 36 },
  "Giannis Antetokounmpo":   { height: "6'11\"", jersey: 34,  team: "MIL", position: "PF", conference: "Eastern", college: "None (HS)",          age: 30 },
  "Nikola Jokic":            { height: "6'11\"", jersey: 15,  team: "DEN", position: "C",  conference: "Western", college: "Serbia (intl)",       age: 30 },
  "Luka Doncic":             { height: "6'7\"",  jersey: 77,  team: "LAL", position: "PG", conference: "Western", college: "Slovenia (intl)",     age: 26 },
  "Jayson Tatum":            { height: "6'8\"",  jersey: 0,   team: "BOS", position: "SF", conference: "Eastern", college: "Duke",                age: 27 },
  "Joel Embiid":             { height: "7'0\"",  jersey: 11,  team: "PHI", position: "C",  conference: "Eastern", college: "Cameroon (intl)",     age: 31 },
  "Shai Gilgeous-Alexander": { height: "6'6\"",  jersey: 2,   team: "OKC", position: "SG", conference: "Western", college: "Kentucky",            age: 27 },
  "Anthony Edwards":         { height: "6'4\"",  jersey: 5,   team: "MIN", position: "SG", conference: "Western", college: "Georgia",             age: 23 },
  "Jaylen Brown":            { height: "6'6\"",  jersey: 7,   team: "BOS", position: "SG", conference: "Eastern", college: "California",          age: 28 },
  "Damian Lillard":          { height: "6'2\"",  jersey: 0,   team: "MIL", position: "PG", conference: "Eastern", college: "Weber State",         age: 34 },
  "Anthony Davis":           { height: "6'10\"", jersey: 3,   team: "LAL", position: "PF", conference: "Western", college: "Kentucky",            age: 32 },
  "Devin Booker":            { height: "6'5\"",  jersey: 1,   team: "PHX", position: "SG", conference: "Western", college: "Kentucky",            age: 28 },
  "Donovan Mitchell":        { height: "6'1\"",  jersey: 45,  team: "CLE", position: "SG", conference: "Eastern", college: "Louisville",          age: 28 },
  "Trae Young":              { height: "6'1\"",  jersey: 11,  team: "ATL", position: "PG", conference: "Eastern", college: "Oklahoma",            age: 26 },
  "Victor Wembanyama":       { height: "7'4\"",  jersey: 1,   team: "SAS", position: "C",  conference: "Western", college: "France (intl)",       age: 21 },
  "Tyrese Haliburton":       { height: "6'5\"",  jersey: 0,   team: "IND", position: "PG", conference: "Eastern", college: "Iowa State",          age: 25 },
  "Ja Morant":               { height: "6'2\"",  jersey: 12,  team: "MEM", position: "PG", conference: "Western", college: "Murray State",        age: 25 },
  "Paolo Banchero":          { height: "6'10\"", jersey: 5,   team: "ORL", position: "PF", conference: "Eastern", college: "Duke",                age: 22 },
  "Jalen Brunson":           { height: "6'1\"",  jersey: 11,  team: "NYK", position: "PG", conference: "Eastern", college: "Villanova",           age: 28 },
  "De'Aaron Fox":            { height: "6'3\"",  jersey: 5,   team: "SAS", position: "PG", conference: "Western", college: "Kentucky",            age: 27 },
  "Bam Adebayo":             { height: "6'9\"",  jersey: 13,  team: "MIA", position: "C",  conference: "Eastern", college: "Kentucky",            age: 27 },
  "Karl-Anthony Towns":      { height: "7'0\"",  jersey: 32,  team: "NYK", position: "C",  conference: "Eastern", college: "Kentucky",            age: 29 },
  "Cade Cunningham":         { height: "6'6\"",  jersey: 2,   team: "DET", position: "PG", conference: "Eastern", college: "Oklahoma State",      age: 23 },
  "Kawhi Leonard":           { height: "6'7\"",  jersey: 2,   team: "LAC", position: "SF", conference: "Western", college: "San Diego State",     age: 33 },
  "Jimmy Butler":            { height: "6'7\"",  jersey: 22,  team: "PHX", position: "SF", conference: "Western", college: "Marquette",           age: 35 },
  "Zion Williamson":         { height: "6'6\"",  jersey: 1,   team: "NOP", position: "PF", conference: "Western", college: "Duke",                age: 24 },
  "James Harden":            { height: "6'5\"",  jersey: 1,   team: "LAC", position: "SG", conference: "Western", college: "Arizona State",       age: 35 },
  "Kyrie Irving":            { height: "6'2\"",  jersey: 11,  team: "DAL", position: "PG", conference: "Western", college: "Duke",                age: 33 },
  "Lauri Markkanen":         { height: "7'0\"",  jersey: 23,  team: "GSW", position: "PF", conference: "Western", college: "Finland (intl)",      age: 28 },
  "Darius Garland":          { height: "6'1\"",  jersey: 10,  team: "CLE", position: "PG", conference: "Eastern", college: "Vanderbilt",          age: 25 },
  "Evan Mobley":             { height: "7'0\"",  jersey: 4,   team: "CLE", position: "PF", conference: "Eastern", college: "USC",                 age: 24 },
  "Jarrett Allen":           { height: "6'11\"", jersey: 31,  team: "CLE", position: "C",  conference: "Eastern", college: "Texas",               age: 27 },
  "Derrick White":           { height: "6'4\"",  jersey: 9,   team: "BOS", position: "SG", conference: "Eastern", college: "Colorado",            age: 31 },
  "Jrue Holiday":            { height: "6'4\"",  jersey: 12,  team: "BOS", position: "PG", conference: "Eastern", college: "UCLA",                age: 35 },
  "Kristaps Porzingis":      { height: "7'2\"",  jersey: 8,   team: "BOS", position: "C",  conference: "Eastern", college: "Latvia (intl)",       age: 29 },
  "Pascal Siakam":           { height: "6'9\"",  jersey: 43,  team: "IND", position: "PF", conference: "Eastern", college: "Cameroon (intl)",     age: 31 },
  "Myles Turner":            { height: "6'11\"", jersey: 33,  team: "IND", position: "C",  conference: "Eastern", college: "Texas",               age: 29 },
  "Franz Wagner":            { height: "6'9\"",  jersey: 21,  team: "ORL", position: "SF", conference: "Eastern", college: "Germany (intl)",      age: 23 },
  "Jalen Williams":          { height: "6'6\"",  jersey: 8,   team: "OKC", position: "SG", conference: "Western", college: "Santa Clara",         age: 23 },
  "Chet Holmgren":           { height: "7'1\"",  jersey: 7,   team: "OKC", position: "C",  conference: "Western", college: "Gonzaga",             age: 23 },
  "Scottie Barnes":          { height: "6'8\"",  jersey: 4,   team: "TOR", position: "SF", conference: "Eastern", college: "Florida State",       age: 24 },
  "Alperen Sengun":          { height: "6'10\"", jersey: 28,  team: "HOU", position: "C",  conference: "Western", college: "Turkey (intl)",       age: 22 },
  "Jalen Green":             { height: "6'4\"",  jersey: 4,   team: "HOU", position: "SG", conference: "Western", college: "None (HS)",           age: 23 },
  "Draymond Green":          { height: "6'6\"",  jersey: 23,  team: "GSW", position: "PF", conference: "Western", college: "Michigan State",      age: 35 },
  "Andrew Wiggins":          { height: "6'7\"",  jersey: 22,  team: "GSW", position: "SF", conference: "Western", college: "Kansas",              age: 30 },
  "Desmond Bane":            { height: "6'6\"",  jersey: 22,  team: "MEM", position: "SG", conference: "Western", college: "TCU",                 age: 26 },
  "Jaren Jackson Jr.":       { height: "6'11\"", jersey: 13,  team: "MEM", position: "PF", conference: "Western", college: "Michigan State",      age: 25 },
  "Mikal Bridges":           { height: "6'6\"",  jersey: 1,   team: "NYK", position: "SF", conference: "Eastern", college: "Villanova",           age: 28 },
  "OG Anunoby":              { height: "6'7\"",  jersey: 8,   team: "NYK", position: "SF", conference: "Eastern", college: "Indiana",             age: 27 },
  "Tyrese Maxey":            { height: "6'2\"",  jersey: 0,   team: "PHI", position: "SG", conference: "Eastern", college: "Kentucky",            age: 24 },
  "Paul George":             { height: "6'8\"",  jersey: 8,   team: "PHI", position: "SF", conference: "Eastern", college: "Fresno State",        age: 35 },
  "Khris Middleton":         { height: "6'8\"",  jersey: 22,  team: "MIL", position: "SF", conference: "Eastern", college: "Texas A&M",           age: 33 },
  "Brook Lopez":             { height: "7'0\"",  jersey: 11,  team: "MIL", position: "C",  conference: "Eastern", college: "Stanford",            age: 37 },
  "Brandon Ingram":          { height: "6'7\"",  jersey: 14,  team: "NOP", position: "SF", conference: "Western", college: "Duke",                age: 27 },
  "CJ McCollum":             { height: "6'3\"",  jersey: 3,   team: "NOP", position: "SG", conference: "Western", college: "Lehigh",              age: 33 },
  "Dejounte Murray":         { height: "6'5\"",  jersey: 5,   team: "NOP", position: "PG", conference: "Western", college: "None (HS)",           age: 28 },
  "LaMelo Ball":             { height: "6'7\"",  jersey: 1,   team: "CHA", position: "PG", conference: "Eastern", college: "None (HS)",           age: 23 },
  "DeMar DeRozan":           { height: "6'6\"",  jersey: 11,  team: "SAC", position: "SF", conference: "Western", college: "USC",                 age: 35 },
  "Domantas Sabonis":        { height: "6'11\"", jersey: 11,  team: "SAC", position: "C",  conference: "Western", college: "Lithuania (intl)",    age: 29 },
  "Rudy Gobert":             { height: "7'1\"",  jersey: 27,  team: "MIN", position: "C",  conference: "Western", college: "France (intl)",       age: 33 },
  "Julius Randle":           { height: "6'9\"",  jersey: 6,   team: "MIN", position: "PF", conference: "Western", college: "Kentucky",            age: 30 },
  "Tyler Herro":             { height: "6'5\"",  jersey: 14,  team: "MIA", position: "SG", conference: "Eastern", college: "Kentucky",            age: 25 },
  "Bradley Beal":            { height: "6'4\"",  jersey: 3,   team: "PHX", position: "SG", conference: "Western", college: "Florida",             age: 32 },
  "Anfernee Simons":         { height: "6'3\"",  jersey: 1,   team: "POR", position: "SG", conference: "Western", college: "None (HS)",           age: 26 },
  "Deandre Ayton":           { height: "7'0\"",  jersey: 2,   team: "POR", position: "C",  conference: "Western", college: "Arizona",             age: 27 },
  "Klay Thompson":           { height: "6'6\"",  jersey: 31,  team: "DAL", position: "SG", conference: "Western", college: "Washington State",    age: 35 },
  "Chris Paul":              { height: "6'0\"",  jersey: 3,   team: "SAS", position: "PG", conference: "Western", college: "Wake Forest",         age: 40 },
  "Aaron Gordon":            { height: "6'8\"",  jersey: 50,  team: "DEN", position: "PF", conference: "Western", college: "Arizona",             age: 30 },
  "Jamal Murray":            { height: "6'4\"",  jersey: 27,  team: "DEN", position: "PG", conference: "Western", college: "Kentucky",            age: 28 },
  "Michael Porter Jr.":      { height: "6'10\"", jersey: 1,   team: "DEN", position: "SF", conference: "Western", college: "Missouri",            age: 27 },
  "Coby White":              { height: "6'4\"",  jersey: 0,   team: "CHI", position: "SG", conference: "Eastern", college: "North Carolina",      age: 25 },
  "Zach LaVine":             { height: "6'5\"",  jersey: 8,   team: "CHI", position: "SG", conference: "Eastern", college: "UCLA",                age: 30 },
  "Nikola Vucevic":          { height: "7'0\"",  jersey: 9,   team: "CHI", position: "C",  conference: "Eastern", college: "Montenegro (intl)",   age: 34 },
  "Jalen Johnson":           { height: "6'9\"",  jersey: 1,   team: "ATL", position: "PF", conference: "Eastern", college: "Duke",                age: 23 },
  "Cam Thomas":              { height: "6'3\"",  jersey: 24,  team: "BKN", position: "SG", conference: "Eastern", college: "Auburn",              age: 23 },
  "Collin Sexton":           { height: "6'1\"",  jersey: 2,   team: "UTA", position: "SG", conference: "Western", college: "Alabama",             age: 26 },
  "Immanuel Quickley":       { height: "6'3\"",  jersey: 5,   team: "TOR", position: "PG", conference: "Eastern", college: "Kentucky",            age: 26 },
  "RJ Barrett":              { height: "6'6\"",  jersey: 9,   team: "TOR", position: "SG", conference: "Eastern", college: "Duke",                age: 25 },
  "Fred VanVleet":           { height: "6'1\"",  jersey: 5,   team: "HOU", position: "PG", conference: "Western", college: "Wichita State",       age: 31 },
  "Jabari Smith Jr.":        { height: "6'10\"", jersey: 10,  team: "HOU", position: "PF", conference: "Western", college: "Auburn",              age: 22 },
  "Amen Thompson":           { height: "6'7\"",  jersey: 1,   team: "HOU", position: "SG", conference: "Western", college: "None (HS)",           age: 22 },
  "Wendell Carter Jr.":      { height: "6'10\"", jersey: 34,  team: "ORL", position: "C",  conference: "Eastern", college: "Duke",                age: 25 },
  "Jalen Suggs":             { height: "6'4\"",  jersey: 4,   team: "ORL", position: "SG", conference: "Eastern", college: "Gonzaga",             age: 23 },
  "Jonathan Kuminga":        { height: "6'8\"",  jersey: 0,   team: "GSW", position: "SF", conference: "Western", college: "None (HS)",           age: 22 },
  "Keegan Murray":           { height: "6'8\"",  jersey: 13,  team: "SAC", position: "SF", conference: "Western", college: "Iowa",                age: 24 },
  "Malik Monk":              { height: "6'3\"",  jersey: 0,   team: "SAC", position: "SG", conference: "Western", college: "Kentucky",            age: 27 },
  "Daniel Gafford":          { height: "6'11\"", jersey: 12,  team: "DAL", position: "C",  conference: "Western", college: "Arkansas",            age: 26 },
  "P.J. Washington":         { height: "6'8\"",  jersey: 25,  team: "DAL", position: "PF", conference: "Western", college: "Kentucky",            age: 27 },
  "Jerami Grant":            { height: "6'8\"",  jersey: 9,   team: "POR", position: "SF", conference: "Western", college: "Syracuse",            age: 31 },
  "Walker Kessler":          { height: "7'1\"",  jersey: 24,  team: "UTA", position: "C",  conference: "Western", college: "Auburn",              age: 23 },
  "Kyle Kuzma":              { height: "6'9\"",  jersey: 33,  team: "WAS", position: "PF", conference: "Eastern", college: "Utah",                age: 30 },
  "Jordan Poole":            { height: "6'4\"",  jersey: 13,  team: "WAS", position: "SG", conference: "Eastern", college: "Michigan",            age: 26 },
  "Miles Bridges":           { height: "6'7\"",  jersey: 0,   team: "CHA", position: "PF", conference: "Eastern", college: "Michigan State",      age: 27 },
  "Brandon Miller":          { height: "6'9\"",  jersey: 24,  team: "CHA", position: "SF", conference: "Eastern", college: "Alabama",             age: 22 },
  "Alex Caruso":             { height: "6'5\"",  jersey: 6,   team: "OKC", position: "SG", conference: "Western", college: "Texas A&M",           age: 31 },
  "Lu Dort":                 { height: "6'4\"",  jersey: 5,   team: "OKC", position: "SG", conference: "Western", college: "Arizona State",       age: 26 },
  "Isaiah Hartenstein":      { height: "7'0\"",  jersey: 55,  team: "OKC", position: "C",  conference: "Western", college: "Germany (intl)",      age: 27 },
  "Tobias Harris":           { height: "6'9\"",  jersey: 12,  team: "DET", position: "PF", conference: "Eastern", college: "Tennessee",           age: 32 },
  "Jaden Ivey":              { height: "6'4\"",  jersey: 23,  team: "DET", position: "SG", conference: "Eastern", college: "Purdue",              age: 23 },
  "Austin Reaves":           { height: "6'5\"",  jersey: 15,  team: "LAL", position: "SG", conference: "Western", college: "Arkansas",            age: 27 },
  "Rui Hachimura":           { height: "6'8\"",  jersey: 28,  team: "LAL", position: "PF", conference: "Western", college: "Japan (intl)",        age: 27 },
  "Bobby Portis":            { height: "6'10\"", jersey: 9,   team: "MIL", position: "PF", conference: "Eastern", college: "Arkansas",            age: 30 },
  "Naz Reid":                { height: "6'9\"",  jersey: 11,  team: "MIN", position: "C",  conference: "Western", college: "LSU",                 age: 25 },
  "Mike Conley":             { height: "6'1\"",  jersey: 10,  team: "MIN", position: "PG", conference: "Western", college: "Ohio State",          age: 38 },
  "Herbert Jones":           { height: "6'8\"",  jersey: 5,   team: "NOP", position: "SF", conference: "Western", college: "Alabama",             age: 26 },
  "Trey Murphy III":         { height: "6'8\"",  jersey: 25,  team: "NOP", position: "SF", conference: "Western", college: "Virginia",            age: 24 },
  "Scoot Henderson":         { height: "6'2\"",  jersey: 0,   team: "POR", position: "PG", conference: "Western", college: "None (HS)",           age: 21 },
  "Nic Claxton":             { height: "6'11\"", jersey: 33,  team: "BKN", position: "C",  conference: "Eastern", college: "Georgia",             age: 25 },
  "Josh Hart":               { height: "6'5\"",  jersey: 3,   team: "NYK", position: "SG", conference: "Eastern", college: "Villanova",           age: 30 },
  "Ivica Zubac":             { height: "7'0\"",  jersey: 40,  team: "LAC", position: "C",  conference: "Western", college: "Bosnia (intl)",       age: 28 },
  "Norman Powell":           { height: "6'4\"",  jersey: 24,  team: "LAC", position: "SG", conference: "Western", college: "UCLA",                age: 32 },
  "Russell Westbrook":       { height: "6'3\"",  jersey: 0,   team: "DEN", position: "PG", conference: "Western", college: "UCLA",                age: 36 },
  "Keldon Johnson":          { height: "6'5\"",  jersey: 3,   team: "SAS", position: "SF", conference: "Western", college: "Kentucky",            age: 26 },
  "Devin Vassell":           { height: "6'5\"",  jersey: 24,  team: "SAS", position: "SG", conference: "Western", college: "Florida State",       age: 25 },
  "Dyson Daniels":           { height: "6'7\"",  jersey: 5,   team: "ATL", position: "SG", conference: "Eastern", college: "Australia (intl)",    age: 22 },
  "Clint Capela":            { height: "6'10\"", jersey: 15,  team: "ATL", position: "C",  conference: "Eastern", college: "Switzerland (intl)",  age: 31 },
  "Terry Rozier":            { height: "6'1\"",  jersey: 2,   team: "MIA", position: "PG", conference: "Eastern", college: "Louisville",          age: 31 },
  "Jaime Jaquez Jr.":        { height: "6'7\"",  jersey: 11,  team: "MIA", position: "SF", conference: "Eastern", college: "UCLA",                age: 24 },
  "Dereck Lively II":        { height: "7'1\"",  jersey: 2,   team: "DAL", position: "C",  conference: "Western", college: "Duke",                age: 20 },
  "Dillon Brooks":           { height: "6'7\"",  jersey: 9,   team: "HOU", position: "SF", conference: "Western", college: "Oregon",              age: 29 },
  "Marcus Smart":            { height: "6'3\"",  jersey: 36,  team: "MEM", position: "PG", conference: "Western", college: "Oklahoma State",      age: 31 },
  "Jalen Duren":             { height: "6'11\"", jersey: 0,   team: "DET", position: "C",  conference: "Eastern", college: "Memphis",             age: 21 },
  "Keyonte George":          { height: "6'4\"",  jersey: 3,   team: "UTA", position: "SG", conference: "Western", college: "Baylor",              age: 21 },
  "Max Strus":               { height: "6'6\"",  jersey: 1,   team: "CLE", position: "SG", conference: "Eastern", college: "Lewis",               age: 29 },
  "Kentavious Caldwell-Pope": { height: "6'5\"", jersey: 5,   team: "ORL", position: "SG", conference: "Eastern", college: "Georgia",             age: 32 },
  "Buddy Hield":             { height: "6'4\"",  jersey: 17,  team: "GSW", position: "SG", conference: "Western", college: "Oklahoma",            age: 32 },
  "Al Horford":              { height: "6'9\"",  jersey: 42,  team: "BOS", position: "C",  conference: "Eastern", college: "Dominican Rep. (intl)", age: 39 },
  "Alexandre Sarr":          { height: "7'0\"",  jersey: 5,   team: "WAS", position: "C",  conference: "Eastern", college: "France (intl)",       age: 21 },
  "Zach Edey":               { height: "7'4\"",  jersey: 14,  team: "MEM", position: "C",  conference: "Western", college: "Purdue",              age: 23 },
  "Mark Williams":           { height: "7'0\"",  jersey: 5,   team: "CHA", position: "C",  conference: "Eastern", college: "Duke",                age: 23 },
  "Bilal Coulibaly":         { height: "6'7\"",  jersey: 0,   team: "WAS", position: "SF", conference: "Eastern", college: "France (intl)",       age: 21 },
  "D'Angelo Russell":        { height: "6'4\"",  jersey: 1,   team: "LAL", position: "PG", conference: "Western", college: "Ohio State",          age: 29 },
  "Harrison Barnes":         { height: "6'8\"",  jersey: 40,  team: "SAS", position: "SF", conference: "Western", college: "North Carolina",      age: 33 },
  "Tari Eason":              { height: "6'8\"",  jersey: 17,  team: "HOU", position: "SF", conference: "Western", college: "LSU",                 age: 23 },
  "Brandin Podziemski":      { height: "6'4\"",  jersey: 2,   team: "GSW", position: "SG", conference: "Western", college: "Santa Clara",         age: 22 },
  "Patrick Williams":        { height: "6'8\"",  jersey: 44,  team: "CHI", position: "PF", conference: "Eastern", college: "Florida State",       age: 23 },
  "John Collins":            { height: "6'9\"",  jersey: 20,  team: "UTA", position: "PF", conference: "Western", college: "Wake Forest",         age: 27 },
  "Nick Richards":           { height: "6'11\"", jersey: 4,   team: "CHA", position: "C",  conference: "Eastern", college: "Kentucky",            age: 26 },
  "Tre Jones":               { height: "6'1\"",  jersey: 33,  team: "SAS", position: "PG", conference: "Western", college: "Duke",                age: 25 },
  "Spencer Dinwiddie":       { height: "6'6\"",  jersey: 26,  team: "DAL", position: "PG", conference: "Western", college: "Colorado",            age: 32 },
  "Jabari Walker":           { height: "6'8\"",  jersey: 34,  team: "POR", position: "PF", conference: "Western", college: "Colorado",            age: 22 },
  "Kevin Huerter":           { height: "6'7\"",  jersey: 9,   team: "SAC", position: "SG", conference: "Western", college: "Maryland",            age: 27 },
  "Grayson Allen":           { height: "6'4\"",  jersey: 7,   team: "PHX", position: "SG", conference: "Western", college: "Duke",                age: 30 },
  "Ausar Thompson":          { height: "6'7\"",  jersey: 5,   team: "DET", position: "SF", conference: "Eastern", college: "None (HS)",           age: 22 },
};

export const NFL_ATTRS: Record<string, NFLAttrs> = {
  "Patrick Mahomes":    { height: "6'3\"",  jersey: 15,  team: "Kansas City Chiefs",     position: "QB",   conference: "AFC", college: "Texas Tech",          age: 29 },
  "Josh Allen":         { height: "6'5\"",  jersey: 17,  team: "Buffalo Bills",           position: "QB",   conference: "AFC", college: "Wyoming",             age: 29 },
  "Lamar Jackson":      { height: "6'2\"",  jersey: 8,   team: "Baltimore Ravens",        position: "QB",   conference: "AFC", college: "Louisville",          age: 28 },
  "Joe Burrow":         { height: "6'4\"",  jersey: 9,   team: "Cincinnati Bengals",      position: "QB",   conference: "AFC", college: "LSU",                 age: 28 },
  "Jalen Hurts":        { height: "6'1\"",  jersey: 1,   team: "Philadelphia Eagles",     position: "QB",   conference: "NFC", college: "Oklahoma",            age: 26 },
  "Justin Herbert":     { height: "6'6\"",  jersey: 10,  team: "Los Angeles Chargers",    position: "QB",   conference: "AFC", college: "Oregon",              age: 27 },
  "Dak Prescott":       { height: "6'2\"",  jersey: 4,   team: "Dallas Cowboys",          position: "QB",   conference: "NFC", college: "Mississippi State",   age: 31 },
  "Tua Tagovailoa":     { height: "6'1\"",  jersey: 1,   team: "Miami Dolphins",          position: "QB",   conference: "AFC", college: "Alabama",             age: 27 },
  "CJ Stroud":          { height: "6'3\"",  jersey: 7,   team: "Houston Texans",          position: "QB",   conference: "AFC", college: "Ohio State",          age: 23 },
  "Brock Purdy":        { height: "6'1\"",  jersey: 13,  team: "San Francisco 49ers",     position: "QB",   conference: "NFC", college: "Iowa State",          age: 25 },
  "Tyreek Hill":        { height: "5'10\"", jersey: 10,  team: "Miami Dolphins",          position: "WR",   conference: "AFC", college: "West Alabama",        age: 31 },
  "Davante Adams":      { height: "6'1\"",  jersey: 17,  team: "New York Jets",           position: "WR",   conference: "AFC", college: "Fresno State",        age: 32 },
  "Justin Jefferson":   { height: "6'1\"",  jersey: 18,  team: "Minnesota Vikings",       position: "WR",   conference: "NFC", college: "LSU",                 age: 26 },
  "Ja'Marr Chase":      { height: "6'0\"",  jersey: 1,   team: "Cincinnati Bengals",      position: "WR",   conference: "AFC", college: "LSU",                 age: 25 },
  "Travis Kelce":       { height: "6'5\"",  jersey: 87,  team: "Kansas City Chiefs",      position: "TE",   conference: "AFC", college: "Cincinnati",          age: 35 },
  "Stefon Diggs":       { height: "6'0\"",  jersey: 14,  team: "Houston Texans",          position: "WR",   conference: "AFC", college: "Maryland",            age: 31 },
  "Cooper Kupp":        { height: "6'2\"",  jersey: 10,  team: "Los Angeles Rams",        position: "WR",   conference: "NFC", college: "Eastern Washington",  age: 32 },
  "Derrick Henry":      { height: "6'3\"",  jersey: 22,  team: "Baltimore Ravens",        position: "RB",   conference: "AFC", college: "Alabama",             age: 31 },
  "Christian McCaffrey": { height: "5'11\"", jersey: 23,  team: "San Francisco 49ers",   position: "RB",   conference: "NFC", college: "Stanford",            age: 28 },
  "Saquon Barkley":     { height: "5'11\"", jersey: 26,  team: "Philadelphia Eagles",     position: "RB",   conference: "NFC", college: "Penn State",          age: 28 },
  "Nick Chubb":         { height: "5'11\"", jersey: 24,  team: "Cleveland Browns",        position: "RB",   conference: "AFC", college: "Georgia",             age: 29 },
  "Josh Jacobs":        { height: "5'10\"", jersey: 8,   team: "Green Bay Packers",       position: "RB",   conference: "NFC", college: "Alabama",             age: 27 },
  "Tony Pollard":       { height: "6'0\"",  jersey: 20,  team: "Tennessee Titans",        position: "RB",   conference: "AFC", college: "Memphis",             age: 28 },
  "Aaron Donald":       { height: "6'1\"",  jersey: 99,  team: "Los Angeles Rams",        position: "DT",   conference: "NFC", college: "Pittsburgh",          age: 33 },
  "Micah Parsons":      { height: "6'3\"",  jersey: 11,  team: "Dallas Cowboys",          position: "EDGE", conference: "NFC", college: "Penn State",          age: 26 },
  "Myles Garrett":      { height: "6'4\"",  jersey: 95,  team: "Cleveland Browns",        position: "EDGE", conference: "AFC", college: "Texas A&M",           age: 29 },
  "TJ Watt":            { height: "6'4\"",  jersey: 90,  team: "Pittsburgh Steelers",     position: "EDGE", conference: "AFC", college: "Wisconsin",           age: 30 },
  "Sam LaPorta":        { height: "6'3\"",  jersey: 80,  team: "Detroit Lions",           position: "TE",   conference: "NFC", college: "Iowa",                age: 24 },
  "Puka Nacua":         { height: "6'1\"",  jersey: 17,  team: "Los Angeles Rams",        position: "WR",   conference: "NFC", college: "BYU",                 age: 24 },
  "Jordan Love":        { height: "6'4\"",  jersey: 10,  team: "Green Bay Packers",       position: "QB",   conference: "NFC", college: "Utah State",          age: 26 },
  "Caleb Williams":     { height: "6'1\"",  jersey: 18,  team: "Chicago Bears",           position: "QB",   conference: "NFC", college: "USC",                 age: 23 },
  "Drake Maye":         { height: "6'4\"",  jersey: 10,  team: "New England Patriots",    position: "QB",   conference: "AFC", college: "North Carolina",      age: 22 },
  "Jayden Daniels":     { height: "6'4\"",  jersey: 5,   team: "Washington Commanders",   position: "QB",   conference: "NFC", college: "LSU",                 age: 24 },
  "Geno Smith":         { height: "6'3\"",  jersey: 7,   team: "Seattle Seahawks",        position: "QB",   conference: "NFC", college: "West Virginia",       age: 34 },
  "Jared Goff":         { height: "6'4\"",  jersey: 16,  team: "Detroit Lions",           position: "QB",   conference: "NFC", college: "California",          age: 30 },
  "Matthew Stafford":   { height: "6'3\"",  jersey: 9,   team: "Los Angeles Rams",        position: "QB",   conference: "NFC", college: "Georgia",             age: 37 },
  "Russell Wilson":     { height: "5'11\"", jersey: 3,   team: "Pittsburgh Steelers",     position: "QB",   conference: "AFC", college: "Wisconsin",           age: 36 },
  "Kirk Cousins":       { height: "6'3\"",  jersey: 8,   team: "Atlanta Falcons",         position: "QB",   conference: "NFC", college: "Michigan State",      age: 37 },
  "Kyler Murray":       { height: "5'10\"", jersey: 1,   team: "Arizona Cardinals",       position: "QB",   conference: "NFC", college: "Oklahoma",            age: 27 },
  "Trevor Lawrence":    { height: "6'6\"",  jersey: 16,  team: "Jacksonville Jaguars",    position: "QB",   conference: "AFC", college: "Clemson",             age: 25 },
  "Sam Darnold":        { height: "6'3\"",  jersey: 14,  team: "Minnesota Vikings",       position: "QB",   conference: "NFC", college: "USC",                 age: 28 },
  "Will Levis":         { height: "6'3\"",  jersey: 8,   team: "Tennessee Titans",        position: "QB",   conference: "AFC", college: "Kentucky",            age: 26 },
  "Anthony Richardson": { height: "6'4\"",  jersey: 5,   team: "Indianapolis Colts",     position: "QB",   conference: "AFC", college: "Florida",             age: 22 },
  "Bryce Young":        { height: "5'10\"", jersey: 9,   team: "Carolina Panthers",       position: "QB",   conference: "NFC", college: "Alabama",             age: 23 },
  "Amon-Ra St. Brown":  { height: "6'1\"",  jersey: 14,  team: "Detroit Lions",           position: "WR",   conference: "NFC", college: "USC",                 age: 25 },
  "Garrett Wilson":     { height: "6'0\"",  jersey: 17,  team: "New York Jets",           position: "WR",   conference: "AFC", college: "Ohio State",          age: 24 },
  "CeeDee Lamb":        { height: "6'2\"",  jersey: 88,  team: "Dallas Cowboys",          position: "WR",   conference: "NFC", college: "Oklahoma",            age: 26 },
  "Drake London":       { height: "6'4\"",  jersey: 5,   team: "Atlanta Falcons",         position: "WR",   conference: "NFC", college: "USC",                 age: 23 },
  "Chris Olave":        { height: "6'1\"",  jersey: 12,  team: "New Orleans Saints",      position: "WR",   conference: "NFC", college: "Ohio State",          age: 24 },
  "Terry McLaurin":     { height: "6'0\"",  jersey: 17,  team: "Washington Commanders",   position: "WR",   conference: "NFC", college: "Ohio State",          age: 29 },
  "George Pickens":     { height: "6'3\"",  jersey: 14,  team: "Pittsburgh Steelers",     position: "WR",   conference: "AFC", college: "Georgia",             age: 24 },
  "Jaylen Waddle":      { height: "5'10\"", jersey: 17,  team: "Miami Dolphins",          position: "WR",   conference: "AFC", college: "Alabama",             age: 26 },
  "Tee Higgins":        { height: "6'4\"",  jersey: 5,   team: "Cincinnati Bengals",      position: "WR",   conference: "AFC", college: "Clemson",             age: 26 },
  "Calvin Ridley":      { height: "6'1\"",  jersey: 0,   team: "Tennessee Titans",        position: "WR",   conference: "AFC", college: "Alabama",             age: 30 },
  "Deebo Samuel":       { height: "5'11\"", jersey: 19,  team: "San Francisco 49ers",     position: "WR",   conference: "NFC", college: "South Carolina",      age: 29 },
  "Keenan Allen":       { height: "6'2\"",  jersey: 13,  team: "Chicago Bears",           position: "WR",   conference: "NFC", college: "California",          age: 33 },
  "DK Metcalf":         { height: "6'4\"",  jersey: 14,  team: "Seattle Seahawks",        position: "WR",   conference: "NFC", college: "Mississippi",         age: 27 },
  "Mike Evans":         { height: "6'5\"",  jersey: 13,  team: "Tampa Bay Buccaneers",    position: "WR",   conference: "NFC", college: "Texas A&M",           age: 31 },
  "Mark Andrews":       { height: "6'5\"",  jersey: 89,  team: "Baltimore Ravens",        position: "TE",   conference: "AFC", college: "Oklahoma",            age: 30 },
  "George Kittle":      { height: "6'4\"",  jersey: 85,  team: "San Francisco 49ers",     position: "TE",   conference: "NFC", college: "Iowa",                age: 31 },
  "Dalton Kincaid":     { height: "6'4\"",  jersey: 86,  team: "Buffalo Bills",           position: "TE",   conference: "AFC", college: "Utah",                age: 26 },
  "Kyle Pitts":         { height: "6'6\"",  jersey: 8,   team: "Atlanta Falcons",         position: "TE",   conference: "NFC", college: "Florida",             age: 24 },
  "Dallas Goedert":     { height: "6'5\"",  jersey: 88,  team: "Philadelphia Eagles",     position: "TE",   conference: "NFC", college: "South Dakota State",  age: 30 },
  "Trey McBride":       { height: "6'4\"",  jersey: 85,  team: "Arizona Cardinals",       position: "TE",   conference: "NFC", college: "Colorado State",      age: 25 },
  "Jake Ferguson":      { height: "6'5\"",  jersey: 87,  team: "Dallas Cowboys",          position: "TE",   conference: "NFC", college: "Wisconsin",           age: 25 },
  "David Njoku":        { height: "6'4\"",  jersey: 85,  team: "Cleveland Browns",        position: "TE",   conference: "AFC", college: "Miami (FL)",          age: 28 },
  "Evan Engram":        { height: "6'3\"",  jersey: 17,  team: "Jacksonville Jaguars",    position: "TE",   conference: "AFC", college: "Mississippi",         age: 30 },
  "Isiah Pacheco":      { height: "5'11\"", jersey: 10,  team: "Kansas City Chiefs",      position: "RB",   conference: "AFC", college: "Rutgers",             age: 26 },
  "De'Von Achane":      { height: "5'9\"",  jersey: 28,  team: "Miami Dolphins",          position: "RB",   conference: "AFC", college: "Texas A&M",           age: 23 },
  "Breece Hall":        { height: "6'1\"",  jersey: 20,  team: "New York Jets",           position: "RB",   conference: "AFC", college: "Iowa State",          age: 24 },
  "Travis Etienne":     { height: "5'10\"", jersey: 1,   team: "Jacksonville Jaguars",    position: "RB",   conference: "AFC", college: "Clemson",             age: 27 },
  "Alvin Kamara":       { height: "5'10\"", jersey: 41,  team: "New Orleans Saints",      position: "RB",   conference: "NFC", college: "Tennessee",           age: 30 },
  "Aaron Jones":        { height: "5'9\"",  jersey: 33,  team: "Minnesota Vikings",       position: "RB",   conference: "NFC", college: "UTEP",                age: 30 },
  "Jonathan Taylor":    { height: "5'10\"", jersey: 28,  team: "Indianapolis Colts",      position: "RB",   conference: "AFC", college: "Wisconsin",           age: 26 },
  "James Cook":         { height: "5'11\"", jersey: 4,   team: "Buffalo Bills",           position: "RB",   conference: "AFC", college: "Georgia",             age: 25 },
  "Joe Mixon":          { height: "6'1\"",  jersey: 28,  team: "Houston Texans",          position: "RB",   conference: "AFC", college: "Oklahoma",            age: 29 },
  "Rachaad White":      { height: "6'0\"",  jersey: 29,  team: "Tampa Bay Buccaneers",    position: "RB",   conference: "NFC", college: "Arizona State",       age: 27 },
  "Bijan Robinson":     { height: "5'11\"", jersey: 7,   team: "Atlanta Falcons",         position: "RB",   conference: "NFC", college: "Texas",               age: 23 },
  "Rhamondre Stevenson": { height: "6'0\"", jersey: 38,  team: "New England Patriots",   position: "RB",   conference: "AFC", college: "Oklahoma",            age: 27 },
  "Tyjae Spears":       { height: "5'10\"", jersey: 32,  team: "Tennessee Titans",        position: "RB",   conference: "AFC", college: "Tulane",              age: 24 },
  "Brian Robinson Jr.": { height: "6'1\"",  jersey: 8,   team: "Washington Commanders",   position: "RB",   conference: "NFC", college: "Alabama",             age: 27 },
  "Chase Brown":        { height: "5'11\"", jersey: 30,  team: "Cincinnati Bengals",      position: "RB",   conference: "AFC", college: "Illinois",            age: 25 },
  "Kyren Williams":     { height: "5'9\"",  jersey: 23,  team: "Los Angeles Rams",        position: "RB",   conference: "NFC", college: "Notre Dame",          age: 25 },
  "Najee Harris":       { height: "6'2\"",  jersey: 22,  team: "Pittsburgh Steelers",     position: "RB",   conference: "AFC", college: "Alabama",             age: 27 },
  "Maxx Crosby":        { height: "6'5\"",  jersey: 98,  team: "Las Vegas Raiders",       position: "EDGE", conference: "AFC", college: "Eastern Michigan",    age: 27 },
  "Haason Reddick":     { height: "6'1\"",  jersey: 7,   team: "New York Jets",           position: "EDGE", conference: "AFC", college: "Temple",              age: 31 },
  "Will Anderson Jr.":  { height: "6'4\"",  jersey: 51,  team: "Houston Texans",          position: "EDGE", conference: "AFC", college: "Alabama",             age: 23 },
  "Brian Burns":        { height: "6'5\"",  jersey: 55,  team: "New York Giants",         position: "EDGE", conference: "NFC", college: "Florida State",       age: 27 },
  "Josh Uche":          { height: "6'2\"",  jersey: 55,  team: "New England Patriots",    position: "EDGE", conference: "AFC", college: "Michigan",            age: 27 },
  "Aidan Hutchinson":   { height: "6'6\"",  jersey: 97,  team: "Detroit Lions",           position: "EDGE", conference: "NFC", college: "Michigan",            age: 25 },
  "Darius Leonard":     { height: "6'2\"",  jersey: 53,  team: "Indianapolis Colts",      position: "LB",   conference: "AFC", college: "South Carolina State", age: 30 },
  "Fred Warner":        { height: "6'3\"",  jersey: 54,  team: "San Francisco 49ers",     position: "LB",   conference: "NFC", college: "BYU",                 age: 28 },
  "Patrick Queen":      { height: "6'0\"",  jersey: 6,   team: "Pittsburgh Steelers",     position: "LB",   conference: "AFC", college: "LSU",                 age: 27 },
  "Lavonte David":      { height: "6'1\"",  jersey: 54,  team: "Tampa Bay Buccaneers",    position: "LB",   conference: "NFC", college: "Nebraska",            age: 35 },
  "Roquan Smith":       { height: "6'1\"",  jersey: 0,   team: "Baltimore Ravens",        position: "LB",   conference: "AFC", college: "Georgia",             age: 28 },
  "Demario Davis":      { height: "6'2\"",  jersey: 56,  team: "New Orleans Saints",      position: "LB",   conference: "NFC", college: "Arkansas State",      age: 36 },
  "Eric Kendricks":     { height: "6'0\"",  jersey: 54,  team: "Dallas Cowboys",          position: "LB",   conference: "NFC", college: "UCLA",                age: 33 },
  "Bobby Wagner":       { height: "6'0\"",  jersey: 45,  team: "Seattle Seahawks",        position: "LB",   conference: "NFC", college: "Utah State",          age: 35 },
  "Jalen Ramsey":       { height: "6'1\"",  jersey: 5,   team: "Los Angeles Rams",        position: "CB",   conference: "NFC", college: "Florida State",       age: 31 },
  "Sauce Gardner":      { height: "6'3\"",  jersey: 1,   team: "New York Jets",           position: "CB",   conference: "AFC", college: "Cincinnati",          age: 24 },
  "Jaire Alexander":    { height: "5'11\"", jersey: 23,  team: "Green Bay Packers",       position: "CB",   conference: "NFC", college: "Louisville",          age: 28 },
  "Patrick Surtain II": { height: "6'2\"",  jersey: 2,   team: "Denver Broncos",          position: "CB",   conference: "AFC", college: "Alabama",             age: 25 },
  "Trevon Diggs":       { height: "6'1\"",  jersey: 7,   team: "Dallas Cowboys",          position: "CB",   conference: "NFC", college: "Alabama",             age: 27 },
  "Marshon Lattimore":  { height: "6'0\"",  jersey: 23,  team: "New Orleans Saints",      position: "CB",   conference: "NFC", college: "Ohio State",          age: 29 },
  "Darius Slay":        { height: "5'11\"", jersey: 2,   team: "Philadelphia Eagles",     position: "CB",   conference: "NFC", college: "Mississippi State",   age: 34 },
  "Tre'Davious White":  { height: "5'11\"", jersey: 27,  team: "Los Angeles Rams",        position: "CB",   conference: "NFC", college: "LSU",                 age: 29 },
  "Justin Simmons":     { height: "6'2\"",  jersey: 31,  team: "Atlanta Falcons",         position: "S",    conference: "NFC", college: "Boston College",      age: 31 },
  "Derwin James":       { height: "6'2\"",  jersey: 3,   team: "Los Angeles Chargers",    position: "S",    conference: "AFC", college: "Florida State",       age: 29 },
  "Marcus Williams":    { height: "6'2\"",  jersey: 38,  team: "Baltimore Ravens",        position: "S",    conference: "AFC", college: "Utah",                age: 29 },
  "Jordan Poyer":       { height: "6'0\"",  jersey: 21,  team: "Miami Dolphins",          position: "S",    conference: "AFC", college: "Oregon State",        age: 34 },
  "Quandre Diggs":      { height: "5'10\"", jersey: 6,   team: "Seattle Seahawks",        position: "S",    conference: "NFC", college: "Texas",               age: 32 },
  "Harrison Smith":     { height: "6'2\"",  jersey: 22,  team: "Minnesota Vikings",       position: "S",    conference: "NFC", college: "Notre Dame",          age: 36 },
  "Kevin Byard":        { height: "5'11\"", jersey: 31,  team: "Philadelphia Eagles",     position: "S",    conference: "NFC", college: "Middle Tennessee",    age: 32 },
  "Budda Baker":        { height: "5'10\"", jersey: 3,   team: "Arizona Cardinals",       position: "S",    conference: "NFC", college: "Washington",          age: 30 },
  "Minkah Fitzpatrick": { height: "6'1\"",  jersey: 39,  team: "Pittsburgh Steelers",     position: "S",    conference: "AFC", college: "Alabama",             age: 28 },
  "Jaquan Brisker":     { height: "6'1\"",  jersey: 9,   team: "Chicago Bears",           position: "S",    conference: "NFC", college: "Penn State",          age: 27 },
  "DeVonta Smith":      { height: "6'0\"",  jersey: 6,   team: "Philadelphia Eagles",     position: "WR",   conference: "NFC", college: "Alabama",             age: 28 },
  "AJ Brown":           { height: "6'1\"",  jersey: 11,  team: "Philadelphia Eagles",     position: "WR",   conference: "NFC", college: "Mississippi",         age: 28 },
  "Diontae Johnson":    { height: "5'10\"", jersey: 18,  team: "Carolina Panthers",       position: "WR",   conference: "NFC", college: "Toledo",              age: 29 },
  "DJ Moore":           { height: "5'11\"", jersey: 2,   team: "Chicago Bears",           position: "WR",   conference: "NFC", college: "Maryland",            age: 28 },
  "Amari Cooper":       { height: "6'1\"",  jersey: 2,   team: "Cleveland Browns",        position: "WR",   conference: "AFC", college: "Alabama",             age: 31 },
  "Marquise Brown":     { height: "5'9\"",  jersey: 2,   team: "Arizona Cardinals",       position: "WR",   conference: "NFC", college: "Oklahoma",            age: 28 },
  "Christian Watson":   { height: "6'4\"",  jersey: 9,   team: "Green Bay Packers",       position: "WR",   conference: "NFC", college: "North Dakota State",  age: 25 },
  "Tank Dell":          { height: "5'8\"",  jersey: 3,   team: "Houston Texans",          position: "WR",   conference: "AFC", college: "Houston",             age: 25 },
  "Rashee Rice":        { height: "6'1\"",  jersey: 4,   team: "Kansas City Chiefs",      position: "WR",   conference: "AFC", college: "SMU",                 age: 24 },
  "Dontayvion Wicks":   { height: "6'1\"",  jersey: 17,  team: "Green Bay Packers",       position: "WR",   conference: "NFC", college: "Virginia",            age: 24 },
  "Jaxon Smith-Njigba": { height: "6'1\"",  jersey: 11,  team: "Seattle Seahawks",        position: "WR",   conference: "NFC", college: "Ohio State",          age: 23 },
  "Michael Pittman Jr.": { height: "6'4\"", jersey: 11,  team: "Indianapolis Colts",     position: "WR",   conference: "AFC", college: "USC",                 age: 27 },
  "Tyler Lockett":      { height: "5'10\"", jersey: 16,  team: "Seattle Seahawks",        position: "WR",   conference: "NFC", college: "Kansas State",        age: 33 },
  "Zay Jones":          { height: "6'2\"",  jersey: 7,   team: "Jacksonville Jaguars",    position: "WR",   conference: "AFC", college: "East Carolina",       age: 30 },
  "Christian Kirk":     { height: "5'11\"", jersey: 13,  team: "Jacksonville Jaguars",    position: "WR",   conference: "AFC", college: "Texas A&M",           age: 28 },
  "Adam Thielen":       { height: "6'2\"",  jersey: 19,  team: "Carolina Panthers",       position: "WR",   conference: "NFC", college: "Minnesota State",     age: 35 },
  "Quentin Johnston":   { height: "6'4\"",  jersey: 1,   team: "Los Angeles Chargers",    position: "WR",   conference: "AFC", college: "TCU",                 age: 24 },
  "Josh Palmer":        { height: "6'2\"",  jersey: 5,   team: "Los Angeles Chargers",    position: "WR",   conference: "AFC", college: "Tennessee",           age: 26 },
  "Hollywood Brown":    { height: "5'11\"", jersey: 17,  team: "Kansas City Chiefs",      position: "WR",   conference: "AFC", college: "Oklahoma",            age: 28 },
  "Xavier Worthy":      { height: "5'11\"", jersey: 1,   team: "Kansas City Chiefs",      position: "WR",   conference: "AFC", college: "Texas",               age: 22 },
  "Devontez Walker":    { height: "6'1\"",  jersey: 16,  team: "Baltimore Ravens",        position: "WR",   conference: "AFC", college: "North Carolina",      age: 23 },
  "Leonard Floyd":      { height: "6'5\"",  jersey: 56,  team: "San Francisco 49ers",     position: "EDGE", conference: "NFC", college: "Georgia",             age: 33 },
  "Chris Jones":        { height: "6'5\"",  jersey: 95,  team: "Kansas City Chiefs",      position: "DT",   conference: "AFC", college: "Mississippi State",   age: 30 },
  "Dexter Lawrence":    { height: "6'4\"",  jersey: 97,  team: "New York Giants",         position: "DT",   conference: "NFC", college: "Clemson",             age: 27 },
  "Quinnen Williams":   { height: "6'3\"",  jersey: 95,  team: "New York Jets",           position: "DT",   conference: "AFC", college: "Alabama",             age: 27 },
  "Cameron Heyward":    { height: "6'5\"",  jersey: 97,  team: "Pittsburgh Steelers",     position: "DT",   conference: "AFC", college: "Ohio State",          age: 36 },
  "Grady Jarrett":      { height: "6'1\"",  jersey: 97,  team: "Atlanta Falcons",         position: "DT",   conference: "NFC", college: "Clemson",             age: 31 },
  "Jeffery Simmons":    { height: "6'4\"",  jersey: 98,  team: "Tennessee Titans",        position: "DT",   conference: "AFC", college: "Mississippi State",   age: 28 },
  "Jonathan Allen":     { height: "6'3\"",  jersey: 93,  team: "Washington Commanders",   position: "DT",   conference: "NFC", college: "Alabama",             age: 30 },
  "Daron Payne":        { height: "6'2\"",  jersey: 94,  team: "Washington Commanders",   position: "DT",   conference: "NFC", college: "Alabama",             age: 28 },
  "Tony Jones Jr.":     { height: "5'11\"", jersey: 34,  team: "Detroit Lions",           position: "RB",   conference: "NFC", college: "Notre Dame",          age: 27 },
};

export const MLB_ATTRS: Record<string, MLBAttrs> = {
  "Shohei Ohtani":         { bat: "Left",   throwing: "Right", country: "Japan",         team: "Los Angeles Dodgers",    position: "DH", division: "NL West",    age: 31 },
  "Mike Trout":            { bat: "Right",  throwing: "Right", country: "USA",           team: "Los Angeles Angels",     position: "CF", division: "AL West",    age: 33 },
  "Mookie Betts":          { bat: "Right",  throwing: "Right", country: "USA",           team: "Los Angeles Dodgers",    position: "SS", division: "NL West",    age: 32 },
  "Freddie Freeman":       { bat: "Left",   throwing: "Right", country: "Canada",        team: "Los Angeles Dodgers",    position: "1B", division: "NL West",    age: 35 },
  "Ronald Acuna Jr.":      { bat: "Right",  throwing: "Right", country: "Venezuela",     team: "Atlanta Braves",         position: "RF", division: "NL East",    age: 27 },
  "Juan Soto":             { bat: "Left",   throwing: "Left",  country: "Dominican Rep.",team: "New York Mets",          position: "RF", division: "NL East",    age: 26 },
  "Fernando Tatis Jr.":    { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "San Diego Padres",       position: "RF", division: "NL West",    age: 26 },
  "Vladimir Guerrero Jr.": { bat: "Right",  throwing: "Right", country: "Canada",        team: "Toronto Blue Jays",      position: "1B", division: "AL East",    age: 26 },
  "Yordan Alvarez":        { bat: "Left",   throwing: "Right", country: "Cuba",          team: "Houston Astros",         position: "DH", division: "AL West",    age: 28 },
  "Trea Turner":           { bat: "Right",  throwing: "Right", country: "USA",           team: "Philadelphia Phillies",  position: "SS", division: "NL East",    age: 32 },
  "Aaron Judge":           { bat: "Right",  throwing: "Right", country: "USA",           team: "New York Yankees",       position: "RF", division: "AL East",    age: 33 },
  "Gerrit Cole":           { bat: "Right",  throwing: "Right", country: "USA",           team: "New York Yankees",       position: "SP", division: "AL East",    age: 34 },
  "Max Scherzer":          { bat: "Right",  throwing: "Right", country: "USA",           team: "Texas Rangers",          position: "SP", division: "AL West",    age: 40 },
  "Jacob deGrom":          { bat: "Left",   throwing: "Right", country: "USA",           team: "Texas Rangers",          position: "SP", division: "AL West",    age: 37 },
  "Clayton Kershaw":       { bat: "Left",   throwing: "Left",  country: "USA",           team: "Los Angeles Dodgers",    position: "SP", division: "NL West",    age: 37 },
  "Spencer Strider":       { bat: "Right",  throwing: "Right", country: "USA",           team: "Atlanta Braves",         position: "SP", division: "NL East",    age: 26 },
  "Julio Rodriguez":       { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "Seattle Mariners",       position: "CF", division: "AL West",    age: 24 },
  "Bobby Witt Jr.":        { bat: "Right",  throwing: "Right", country: "USA",           team: "Kansas City Royals",     position: "SS", division: "AL Central", age: 25 },
  "Gunnar Henderson":      { bat: "Left",   throwing: "Right", country: "USA",           team: "Baltimore Orioles",      position: "SS", division: "AL East",    age: 24 },
  "Bryce Harper":          { bat: "Left",   throwing: "Right", country: "USA",           team: "Philadelphia Phillies",  position: "1B", division: "NL East",    age: 32 },
  "Nolan Arenado":         { bat: "Right",  throwing: "Right", country: "USA",           team: "St. Louis Cardinals",    position: "3B", division: "NL Central", age: 34 },
  "Jose Ramirez":          { bat: "Switch", throwing: "Right", country: "Dominican Rep.",team: "Cleveland Guardians",    position: "3B", division: "AL Central", age: 32 },
  "Manny Machado":         { bat: "Right",  throwing: "Right", country: "USA",           team: "San Diego Padres",       position: "3B", division: "NL West",    age: 32 },
  "Paul Goldschmidt":      { bat: "Right",  throwing: "Right", country: "USA",           team: "St. Louis Cardinals",    position: "1B", division: "NL Central", age: 37 },
  "Pete Alonso":           { bat: "Right",  throwing: "Right", country: "USA",           team: "New York Mets",          position: "1B", division: "NL East",    age: 30 },
  "Francisco Lindor":      { bat: "Switch", throwing: "Right", country: "Puerto Rico",   team: "New York Mets",          position: "SS", division: "NL East",    age: 31 },
  "Corey Seager":          { bat: "Left",   throwing: "Right", country: "USA",           team: "Texas Rangers",          position: "SS", division: "AL West",    age: 31 },
  "Marcus Semien":         { bat: "Right",  throwing: "Right", country: "USA",           team: "Texas Rangers",          position: "2B", division: "AL West",    age: 34 },
  "Xander Bogaerts":       { bat: "Right",  throwing: "Right", country: "Netherlands",   team: "San Diego Padres",       position: "SS", division: "NL West",    age: 32 },
  "Dansby Swanson":        { bat: "Right",  throwing: "Right", country: "USA",           team: "Chicago Cubs",           position: "SS", division: "NL Central", age: 31 },
  "Bo Bichette":           { bat: "Right",  throwing: "Right", country: "USA",           team: "Toronto Blue Jays",      position: "SS", division: "AL East",    age: 27 },
  "Jazz Chisholm Jr.":     { bat: "Left",   throwing: "Right", country: "Bahamas",       team: "New York Yankees",       position: "3B", division: "AL East",    age: 27 },
  "Ha-Seong Kim":          { bat: "Right",  throwing: "Right", country: "South Korea",   team: "San Diego Padres",       position: "2B", division: "NL West",    age: 29 },
  "Ozzie Albies":          { bat: "Switch", throwing: "Right", country: "Curacao",       team: "Atlanta Braves",         position: "2B", division: "NL East",    age: 28 },
  "Jeff McNeil":           { bat: "Left",   throwing: "Right", country: "USA",           team: "New York Mets",          position: "2B", division: "NL East",    age: 33 },
  "Gleyber Torres":        { bat: "Right",  throwing: "Right", country: "Venezuela",     team: "New York Yankees",       position: "2B", division: "AL East",    age: 28 },
  "Ian Happ":              { bat: "Switch", throwing: "Right", country: "USA",           team: "Chicago Cubs",           position: "LF", division: "NL Central", age: 30 },
  "Kyle Tucker":           { bat: "Left",   throwing: "Right", country: "USA",           team: "Houston Astros",         position: "RF", division: "AL West",    age: 28 },
  "Starling Marte":        { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "New York Mets",          position: "RF", division: "NL East",    age: 36 },
  "Teoscar Hernandez":     { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "Los Angeles Dodgers",    position: "RF", division: "NL West",    age: 32 },
  "Michael Harris II":     { bat: "Left",   throwing: "Left",  country: "USA",           team: "Atlanta Braves",         position: "CF", division: "NL East",    age: 24 },
  "Christian Yelich":      { bat: "Left",   throwing: "Right", country: "USA",           team: "Milwaukee Brewers",      position: "LF", division: "NL Central", age: 33 },
  "Willy Adames":          { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "Milwaukee Brewers",      position: "SS", division: "NL Central", age: 30 },
  "Corbin Carroll":        { bat: "Left",   throwing: "Left",  country: "USA",           team: "Arizona Diamondbacks",   position: "CF", division: "NL West",    age: 24 },
  "Josh Bell":             { bat: "Switch", throwing: "Right", country: "USA",           team: "Cleveland Guardians",    position: "1B", division: "AL Central", age: 32 },
  "Anthony Rizzo":         { bat: "Left",   throwing: "Left",  country: "USA",           team: "New York Yankees",       position: "1B", division: "AL East",    age: 35 },
  "Matt Olson":            { bat: "Left",   throwing: "Right", country: "USA",           team: "Atlanta Braves",         position: "1B", division: "NL East",    age: 31 },
  "Ryan Mountcastle":      { bat: "Left",   throwing: "Right", country: "USA",           team: "Baltimore Orioles",      position: "1B", division: "AL East",    age: 28 },
  "CJ Cron":               { bat: "Right",  throwing: "Right", country: "USA",           team: "Colorado Rockies",       position: "1B", division: "NL West",    age: 35 },
  "Luis Arraez":           { bat: "Left",   throwing: "Right", country: "Venezuela",     team: "San Diego Padres",       position: "2B", division: "NL West",    age: 28 },
  "Whit Merrifield":       { bat: "Right",  throwing: "Right", country: "USA",           team: "Philadelphia Phillies",  position: "2B", division: "NL East",    age: 36 },
  "Nico Hoerner":          { bat: "Right",  throwing: "Right", country: "USA",           team: "Chicago Cubs",           position: "2B", division: "NL Central", age: 28 },
  "Jorge Polanco":         { bat: "Switch", throwing: "Right", country: "Dominican Rep.",team: "Seattle Mariners",       position: "2B", division: "AL West",    age: 31 },
  "DJ LeMahieu":           { bat: "Right",  throwing: "Right", country: "USA",           team: "New York Yankees",       position: "2B", division: "AL East",    age: 37 },
  "Brandon Crawford":      { bat: "Left",   throwing: "Right", country: "USA",           team: "St. Louis Cardinals",    position: "SS", division: "NL Central", age: 38 },
  "Tim Anderson":          { bat: "Right",  throwing: "Right", country: "USA",           team: "Chicago White Sox",      position: "SS", division: "AL Central", age: 32 },
  "Nick Senzel":           { bat: "Right",  throwing: "Right", country: "USA",           team: "Cincinnati Reds",        position: "2B", division: "NL Central", age: 30 },
  "Will Smith":            { bat: "Right",  throwing: "Right", country: "USA",           team: "Los Angeles Dodgers",    position: "C",  division: "NL West",    age: 30 },
  "Adley Rutschman":       { bat: "Switch", throwing: "Right", country: "USA",           team: "Baltimore Orioles",      position: "C",  division: "AL East",    age: 27 },
  "Cal Raleigh":           { bat: "Both",   throwing: "Right", country: "USA",           team: "Seattle Mariners",       position: "C",  division: "AL West",    age: 28 },
  "William Contreras":     { bat: "Right",  throwing: "Right", country: "Venezuela",     team: "Milwaukee Brewers",      position: "C",  division: "NL Central", age: 27 },
  "MJ Melendez":           { bat: "Left",   throwing: "Right", country: "USA",           team: "Kansas City Royals",     position: "C",  division: "AL Central", age: 26 },
  "Salvador Perez":        { bat: "Right",  throwing: "Right", country: "Venezuela",     team: "Kansas City Royals",     position: "C",  division: "AL Central", age: 35 },
  "Alejandro Kirk":        { bat: "Right",  throwing: "Right", country: "Mexico",        team: "Toronto Blue Jays",      position: "C",  division: "AL East",    age: 26 },
  "Gary Sanchez":          { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "Minnesota Twins",        position: "C",  division: "AL Central", age: 32 },
  "Austin Riley":          { bat: "Right",  throwing: "Right", country: "USA",           team: "Atlanta Braves",         position: "3B", division: "NL East",    age: 28 },
  "Rafael Devers":         { bat: "Left",   throwing: "Right", country: "Dominican Rep.",team: "Boston Red Sox",         position: "3B", division: "AL East",    age: 28 },
  "Eugenio Suarez":        { bat: "Right",  throwing: "Right", country: "Venezuela",     team: "Seattle Mariners",       position: "3B", division: "AL West",    age: 34 },
  "Ryan McMahon":          { bat: "Left",   throwing: "Right", country: "USA",           team: "Colorado Rockies",       position: "3B", division: "NL West",    age: 30 },
  "Josh Donaldson":        { bat: "Right",  throwing: "Right", country: "USA",           team: "New York Yankees",       position: "3B", division: "AL East",    age: 39 },
  "Jake Cronenworth":      { bat: "Left",   throwing: "Right", country: "USA",           team: "San Diego Padres",       position: "3B", division: "NL West",    age: 31 },
  "Noelvi Marte":          { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "Cincinnati Reds",        position: "3B", division: "NL Central", age: 23 },
  "Nathaniel Lowe":        { bat: "Left",   throwing: "Right", country: "USA",           team: "Texas Rangers",          position: "1B", division: "AL West",    age: 30 },
  "David Peralta":         { bat: "Left",   throwing: "Left",  country: "Venezuela",     team: "Los Angeles Dodgers",    position: "LF", division: "NL West",    age: 38 },
  "Alex Verdugo":          { bat: "Left",   throwing: "Right", country: "Mexico",        team: "New York Yankees",       position: "LF", division: "AL East",    age: 29 },
  "Bryan Reynolds":        { bat: "Switch", throwing: "Right", country: "USA",           team: "Pittsburgh Pirates",     position: "CF", division: "NL Central", age: 30 },
  "Randy Arozarena":       { bat: "Right",  throwing: "Right", country: "Cuba",          team: "Tampa Bay Rays",         position: "LF", division: "AL East",    age: 30 },
  "Adolis Garcia":         { bat: "Right",  throwing: "Right", country: "Cuba",          team: "Texas Rangers",          position: "RF", division: "AL West",    age: 32 },
  "Jake McCarthy":         { bat: "Left",   throwing: "Left",  country: "USA",           team: "Arizona Diamondbacks",   position: "LF", division: "NL West",    age: 27 },
  "Daulton Varsho":        { bat: "Left",   throwing: "Right", country: "USA",           team: "Toronto Blue Jays",      position: "CF", division: "AL East",    age: 28 },
  "Max Kepler":            { bat: "Left",   throwing: "Left",  country: "Germany",       team: "Minnesota Twins",        position: "RF", division: "AL Central", age: 32 },
  "JD Martinez":           { bat: "Right",  throwing: "Right", country: "USA",           team: "New York Mets",          position: "DH", division: "NL East",    age: 37 },
  "Tyler O'Neill":         { bat: "Right",  throwing: "Right", country: "Canada",        team: "Boston Red Sox",         position: "LF", division: "AL East",    age: 30 },
  "Jesus Luzardo":         { bat: "Left",   throwing: "Left",  country: "Panama",        team: "Philadelphia Phillies",  position: "SP", division: "NL East",    age: 27 },
  "Logan Webb":            { bat: "Right",  throwing: "Right", country: "USA",           team: "San Francisco Giants",   position: "SP", division: "NL West",    age: 28 },
  "Pablo Lopez":           { bat: "Right",  throwing: "Right", country: "Venezuela",     team: "Minnesota Twins",        position: "SP", division: "AL Central", age: 29 },
  "Tyler Glasnow":         { bat: "Right",  throwing: "Right", country: "USA",           team: "Los Angeles Dodgers",    position: "SP", division: "NL West",    age: 32 },
  "Framber Valdez":        { bat: "Left",   throwing: "Left",  country: "Dominican Rep.",team: "Houston Astros",         position: "SP", division: "AL West",    age: 31 },
  "Kodai Senga":           { bat: "Right",  throwing: "Right", country: "Japan",         team: "New York Mets",          position: "SP", division: "NL East",    age: 32 },
  "Kevin Gausman":         { bat: "Left",   throwing: "Right", country: "USA",           team: "Toronto Blue Jays",      position: "SP", division: "AL East",    age: 34 },
  "Dylan Cease":           { bat: "Right",  throwing: "Right", country: "USA",           team: "San Diego Padres",       position: "SP", division: "NL West",    age: 29 },
  "Sandy Alcantara":       { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "Miami Marlins",          position: "SP", division: "NL East",    age: 29 },
  "Corbin Burnes":         { bat: "Right",  throwing: "Right", country: "USA",           team: "Baltimore Orioles",      position: "SP", division: "AL East",    age: 30 },
  "Zac Gallen":            { bat: "Right",  throwing: "Right", country: "USA",           team: "Arizona Diamondbacks",   position: "SP", division: "NL West",    age: 29 },
  "MacKenzie Gore":        { bat: "Left",   throwing: "Left",  country: "USA",           team: "Washington Nationals",   position: "SP", division: "NL East",    age: 26 },
  "Nestor Cortes":         { bat: "Right",  throwing: "Left",  country: "Cuba",          team: "New York Yankees",       position: "SP", division: "AL East",    age: 30 },
  "Cristian Javier":       { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "Houston Astros",         position: "SP", division: "AL West",    age: 28 },
  "Hunter Greene":         { bat: "Right",  throwing: "Right", country: "USA",           team: "Cincinnati Reds",        position: "SP", division: "NL Central", age: 25 },
  "George Kirby":          { bat: "Right",  throwing: "Right", country: "USA",           team: "Seattle Mariners",       position: "SP", division: "AL West",    age: 27 },
  "Ranger Suarez":         { bat: "Left",   throwing: "Left",  country: "Venezuela",     team: "Philadelphia Phillies",  position: "SP", division: "NL East",    age: 29 },
  "Brandon Woodruff":      { bat: "Right",  throwing: "Right", country: "USA",           team: "Milwaukee Brewers",      position: "SP", division: "NL Central", age: 32 },
  "Sonny Gray":            { bat: "Right",  throwing: "Right", country: "USA",           team: "Minnesota Twins",        position: "SP", division: "AL Central", age: 35 },
  "Eduardo Rodriguez":     { bat: "Left",   throwing: "Left",  country: "Venezuela",     team: "Arizona Diamondbacks",   position: "SP", division: "NL West",    age: 32 },
  "Emmett Sheehan":        { bat: "Right",  throwing: "Right", country: "USA",           team: "Los Angeles Dodgers",    position: "SP", division: "NL West",    age: 24 },
  "Drew Smyly":            { bat: "Left",   throwing: "Left",  country: "USA",           team: "Atlanta Braves",         position: "SP", division: "NL East",    age: 36 },
  "Bailey Ober":           { bat: "Right",  throwing: "Right", country: "USA",           team: "Minnesota Twins",        position: "SP", division: "AL Central", age: 29 },
  "Josh Hader":            { bat: "Left",   throwing: "Left",  country: "USA",           team: "Houston Astros",         position: "RP", division: "AL West",    age: 31 },
  "Ryan Helsley":          { bat: "Right",  throwing: "Right", country: "USA",           team: "St. Louis Cardinals",    position: "RP", division: "NL Central", age: 30 },
  "Edwin Diaz":            { bat: "Right",  throwing: "Right", country: "Puerto Rico",   team: "New York Mets",          position: "RP", division: "NL East",    age: 31 },
  "Devin Williams":        { bat: "Right",  throwing: "Right", country: "USA",           team: "Milwaukee Brewers",      position: "RP", division: "NL Central", age: 30 },
  "Alexis Diaz":           { bat: "Right",  throwing: "Right", country: "Puerto Rico",   team: "Cincinnati Reds",        position: "RP", division: "NL Central", age: 29 },
  "Emmanuel Clase":        { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "Cleveland Guardians",    position: "RP", division: "AL Central", age: 27 },
  "Kenley Jansen":         { bat: "Both",   throwing: "Right", country: "Netherlands",   team: "Boston Red Sox",         position: "RP", division: "AL East",    age: 37 },
  "Camilo Doval":          { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "San Francisco Giants",   position: "RP", division: "NL West",    age: 28 },
  "Clay Holmes":           { bat: "Right",  throwing: "Right", country: "USA",           team: "New York Yankees",       position: "RP", division: "AL East",    age: 32 },
  "Jordan Romano":         { bat: "Right",  throwing: "Right", country: "Canada",        team: "Toronto Blue Jays",      position: "RP", division: "AL East",    age: 32 },
  "Felix Bautista":        { bat: "Right",  throwing: "Right", country: "Dominican Rep.",team: "Baltimore Orioles",      position: "RP", division: "AL East",    age: 29 },
  "Pete Fairbanks":        { bat: "Right",  throwing: "Right", country: "USA",           team: "Tampa Bay Rays",         position: "RP", division: "AL East",    age: 31 },
  "Michael Brantley":      { bat: "Left",   throwing: "Left",  country: "USA",           team: "Houston Astros",         position: "LF", division: "AL West",    age: 38 },
};

export const NHL_ATTRS: Record<string, NHLAttrs> = {
  "Connor McDavid":       { height: "6'1\"",  jersey: 97,  team: "Edmonton Oilers",       position: "C",  conference: "Western", country: "Canada",      age: 28 },
  "Nathan MacKinnon":     { height: "6'0\"",  jersey: 29,  team: "Colorado Avalanche",    position: "C",  conference: "Western", country: "Canada",      age: 29 },
  "Leon Draisaitl":       { height: "6'2\"",  jersey: 29,  team: "Edmonton Oilers",       position: "C",  conference: "Western", country: "Germany",     age: 29 },
  "Auston Matthews":      { height: "6'3\"",  jersey: 34,  team: "Toronto Maple Leafs",   position: "C",  conference: "Eastern", country: "USA",         age: 27 },
  "David Pastrnak":       { height: "6'0\"",  jersey: 88,  team: "Boston Bruins",         position: "RW", conference: "Eastern", country: "Czech Rep.",  age: 29 },
  "Sidney Crosby":        { height: "5'11\"", jersey: 87,  team: "Pittsburgh Penguins",   position: "C",  conference: "Eastern", country: "Canada",      age: 37 },
  "Alex Ovechkin":        { height: "6'3\"",  jersey: 8,   team: "Washington Capitals",   position: "LW", conference: "Eastern", country: "Russia",      age: 39 },
  "Nikita Kucherov":      { height: "5'11\"", jersey: 86,  team: "Tampa Bay Lightning",   position: "RW", conference: "Eastern", country: "Russia",      age: 31 },
  "Cale Makar":           { height: "5'11\"", jersey: 8,   team: "Colorado Avalanche",    position: "D",  conference: "Western", country: "Canada",      age: 26 },
  "Quinn Hughes":         { height: "5'10\"", jersey: 43,  team: "Vancouver Canucks",     position: "D",  conference: "Western", country: "USA",         age: 25 },
  "Igor Shesterkin":      { height: "6'1\"",  jersey: 31,  team: "New York Rangers",      position: "G",  conference: "Eastern", country: "Russia",      age: 29 },
  "Andrei Vasilevskiy":   { height: "6'3\"",  jersey: 88,  team: "Tampa Bay Lightning",   position: "G",  conference: "Eastern", country: "Russia",      age: 31 },
  "Artemi Panarin":       { height: "6'1\"",  jersey: 10,  team: "New York Rangers",      position: "LW", conference: "Eastern", country: "Russia",      age: 33 },
  "Mitchell Marner":      { height: "6'0\"",  jersey: 16,  team: "Toronto Maple Leafs",   position: "RW", conference: "Eastern", country: "Canada",      age: 28 },
  "Brad Marchand":        { height: "5'9\"",  jersey: 63,  team: "Boston Bruins",         position: "LW", conference: "Eastern", country: "Canada",      age: 37 },
  "Mark Scheifele":       { height: "6'3\"",  jersey: 55,  team: "Winnipeg Jets",         position: "C",  conference: "Western", country: "Canada",      age: 32 },
  "Kyle Connor":          { height: "6'1\"",  jersey: 81,  team: "Winnipeg Jets",         position: "LW", conference: "Western", country: "USA",         age: 28 },
  "Gabriel Landeskog":    { height: "6'1\"",  jersey: 92,  team: "Colorado Avalanche",    position: "LW", conference: "Western", country: "Sweden",      age: 32 },
  "Elias Pettersson":     { height: "6'2\"",  jersey: 40,  team: "Vancouver Canucks",     position: "C",  conference: "Western", country: "Sweden",      age: 26 },
  "Matthew Tkachuk":      { height: "6'2\"",  jersey: 19,  team: "Florida Panthers",      position: "LW", conference: "Eastern", country: "USA",         age: 27 },
  "Sam Reinhart":         { height: "6'2\"",  jersey: 13,  team: "Florida Panthers",      position: "RW", conference: "Eastern", country: "Canada",      age: 29 },
  "Aleksander Barkov":    { height: "6'3\"",  jersey: 16,  team: "Florida Panthers",      position: "C",  conference: "Eastern", country: "Finland",     age: 30 },
  "Jonathan Huberdeau":   { height: "6'1\"",  jersey: 10,  team: "Calgary Flames",        position: "LW", conference: "Western", country: "Canada",      age: 32 },
  "Nazem Kadri":          { height: "6'0\"",  jersey: 91,  team: "Calgary Flames",        position: "C",  conference: "Western", country: "Canada",      age: 34 },
  "Rasmus Dahlin":        { height: "6'3\"",  jersey: 26,  team: "Buffalo Sabres",        position: "D",  conference: "Eastern", country: "Sweden",      age: 25 },
  "Jason Robertson":      { height: "6'2\"",  jersey: 21,  team: "Dallas Stars",          position: "LW", conference: "Western", country: "USA",         age: 25 },
  "Roope Hintz":          { height: "6'3\"",  jersey: 24,  team: "Dallas Stars",          position: "C",  conference: "Western", country: "Finland",     age: 28 },
  "Miro Heiskanen":       { height: "6'1\"",  jersey: 4,   team: "Dallas Stars",          position: "D",  conference: "Western", country: "Finland",     age: 26 },
  "Jake Oettinger":       { height: "6'5\"",  jersey: 29,  team: "Dallas Stars",          position: "G",  conference: "Western", country: "USA",         age: 26 },
  "Roman Josi":           { height: "6'1\"",  jersey: 59,  team: "Nashville Predators",   position: "D",  conference: "Western", country: "Switzerland", age: 34 },
  "Filip Forsberg":       { height: "6'1\"",  jersey: 9,   team: "Nashville Predators",   position: "LW", conference: "Western", country: "Sweden",      age: 33 },
  "Juuse Saros":          { height: "5'11\"", jersey: 74,  team: "Nashville Predators",   position: "G",  conference: "Western", country: "Finland",     age: 30 },
  "Tomas Hertl":          { height: "6'2\"",  jersey: 48,  team: "San Jose Sharks",       position: "C",  conference: "Western", country: "Czech Rep.",  age: 31 },
  "Erik Karlsson":        { height: "6'0\"",  jersey: 65,  team: "Pittsburgh Penguins",   position: "D",  conference: "Eastern", country: "Sweden",      age: 35 },
  "Brock Boeser":         { height: "6'1\"",  jersey: 6,   team: "Vancouver Canucks",     position: "RW", conference: "Western", country: "USA",         age: 28 },
  "Brady Tkachuk":        { height: "6'3\"",  jersey: 7,   team: "Ottawa Senators",       position: "LW", conference: "Eastern", country: "USA",         age: 25 },
  "Tim Stutzle":          { height: "6'2\"",  jersey: 18,  team: "Ottawa Senators",       position: "C",  conference: "Eastern", country: "Germany",     age: 23 },
  "Thomas Chabot":        { height: "6'2\"",  jersey: 72,  team: "Ottawa Senators",       position: "D",  conference: "Eastern", country: "Canada",      age: 28 },
  "Anze Kopitar":         { height: "6'3\"",  jersey: 11,  team: "Los Angeles Kings",     position: "C",  conference: "Western", country: "Slovenia",    age: 37 },
  "Drew Doughty":         { height: "6'1\"",  jersey: 8,   team: "Los Angeles Kings",     position: "D",  conference: "Western", country: "Canada",      age: 35 },
  "Cam Talbot":           { height: "6'4\"",  jersey: 39,  team: "Los Angeles Kings",     position: "G",  conference: "Western", country: "Canada",      age: 38 },
  "JT Miller":            { height: "6'1\"",  jersey: 9,   team: "Vancouver Canucks",     position: "C",  conference: "Western", country: "USA",         age: 32 },
  "Elias Lindholm":       { height: "6'1\"",  jersey: 28,  team: "Boston Bruins",         position: "C",  conference: "Eastern", country: "Sweden",      age: 30 },
  "Sebastian Aho":        { height: "6'1\"",  jersey: 20,  team: "Carolina Hurricanes",   position: "C",  conference: "Eastern", country: "Finland",     age: 28 },
  "Andrei Svechnikov":    { height: "6'2\"",  jersey: 37,  team: "Carolina Hurricanes",   position: "RW", conference: "Eastern", country: "Russia",      age: 25 },
  "Frederik Andersen":    { height: "6'4\"",  jersey: 31,  team: "Carolina Hurricanes",   position: "G",  conference: "Eastern", country: "Denmark",     age: 35 },
  "Brent Burns":          { height: "6'5\"",  jersey: 8,   team: "Carolina Hurricanes",   position: "D",  conference: "Eastern", country: "Canada",      age: 40 },
  "Jordan Staal":         { height: "6'4\"",  jersey: 11,  team: "Carolina Hurricanes",   position: "C",  conference: "Eastern", country: "Canada",      age: 37 },
  "Moritz Seider":        { height: "6'4\"",  jersey: 53,  team: "Detroit Red Wings",     position: "D",  conference: "Eastern", country: "Germany",     age: 24 },
  "Dylan Larkin":         { height: "6'1\"",  jersey: 71,  team: "Detroit Red Wings",     position: "C",  conference: "Eastern", country: "USA",         age: 29 },
  "Ville Husso":          { height: "6'3\"",  jersey: 35,  team: "Detroit Red Wings",     position: "G",  conference: "Eastern", country: "Finland",     age: 30 },
  "Lucas Raymond":        { height: "5'11\"", jersey: 23,  team: "Detroit Red Wings",     position: "RW", conference: "Eastern", country: "Sweden",      age: 23 },
  "Rickard Rakell":       { height: "6'1\"",  jersey: 67,  team: "Pittsburgh Penguins",   position: "RW", conference: "Eastern", country: "Sweden",      age: 32 },
  "Evgeni Malkin":        { height: "6'3\"",  jersey: 71,  team: "Pittsburgh Penguins",   position: "C",  conference: "Eastern", country: "Russia",      age: 38 },
  "Bryan Rust":           { height: "5'11\"", jersey: 17,  team: "Pittsburgh Penguins",   position: "RW", conference: "Eastern", country: "USA",         age: 33 },
  "Jordan Kyrou":         { height: "6'0\"",  jersey: 25,  team: "St. Louis Blues",       position: "RW", conference: "Western", country: "Canada",      age: 27 },
  "Brayden Schenn":       { height: "6'1\"",  jersey: 10,  team: "St. Louis Blues",       position: "C",  conference: "Western", country: "Canada",      age: 34 },
  "Thomas Harley":        { height: "6'3\"",  jersey: 55,  team: "Dallas Stars",          position: "D",  conference: "Western", country: "Canada",      age: 24 },
  "Kirill Kaprizov":      { height: "5'9\"",  jersey: 97,  team: "Minnesota Wild",        position: "LW", conference: "Western", country: "Russia",      age: 28 },
  "Ryan Suter":           { height: "6'1\"",  jersey: 20,  team: "Minnesota Wild",        position: "D",  conference: "Western", country: "USA",         age: 40 },
  "Marc-Andre Fleury":    { height: "6'2\"",  jersey: 29,  team: "Minnesota Wild",        position: "G",  conference: "Western", country: "Canada",      age: 40 },
  "Ryan Hartman":         { height: "5'11\"", jersey: 38,  team: "Minnesota Wild",        position: "RW", conference: "Western", country: "USA",         age: 31 },
  "Joel Eriksson Ek":     { height: "6'3\"",  jersey: 14,  team: "Minnesota Wild",        position: "C",  conference: "Western", country: "Sweden",      age: 28 },
  "Ryan Nugent-Hopkins":  { height: "6'0\"",  jersey: 93,  team: "Edmonton Oilers",       position: "LW", conference: "Western", country: "Canada",      age: 32 },
  "Zach Hyman":           { height: "6'1\"",  jersey: 18,  team: "Edmonton Oilers",       position: "LW", conference: "Western", country: "Canada",      age: 33 },
  "Darnell Nurse":        { height: "6'4\"",  jersey: 25,  team: "Edmonton Oilers",       position: "D",  conference: "Western", country: "Canada",      age: 30 },
  "Stuart Skinner":       { height: "6'4\"",  jersey: 74,  team: "Edmonton Oilers",       position: "G",  conference: "Western", country: "Canada",      age: 26 },
  "Devon Toews":          { height: "6'1\"",  jersey: 7,   team: "Colorado Avalanche",    position: "D",  conference: "Western", country: "Canada",      age: 31 },
  "Mikko Rantanen":       { height: "6'4\"",  jersey: 96,  team: "Colorado Avalanche",    position: "RW", conference: "Western", country: "Finland",     age: 28 },
  "Darcy Kuemper":        { height: "6'5\"",  jersey: 35,  team: "Washington Capitals",   position: "G",  conference: "Eastern", country: "Canada",      age: 35 },
  "Tom Wilson":           { height: "6'4\"",  jersey: 43,  team: "Washington Capitals",   position: "RW", conference: "Eastern", country: "Canada",      age: 31 },
  "Nicklas Backstrom":    { height: "6'1\"",  jersey: 19,  team: "Washington Capitals",   position: "C",  conference: "Eastern", country: "Sweden",      age: 37 },
  "John Carlson":         { height: "6'3\"",  jersey: 74,  team: "Washington Capitals",   position: "D",  conference: "Eastern", country: "USA",         age: 35 },
  "Oliver Wahlstrom":     { height: "6'1\"",  jersey: 26,  team: "New York Islanders",    position: "RW", conference: "Eastern", country: "USA",         age: 24 },
  "Mathew Barzal":        { height: "6'0\"",  jersey: 13,  team: "New York Islanders",    position: "C",  conference: "Eastern", country: "Canada",      age: 28 },
  "Ilya Sorokin":         { height: "6'3\"",  jersey: 30,  team: "New York Islanders",    position: "G",  conference: "Eastern", country: "Russia",      age: 29 },
  "Noah Dobson":          { height: "6'4\"",  jersey: 8,   team: "New York Islanders",    position: "D",  conference: "Eastern", country: "Canada",      age: 25 },
  "Jack Hughes":          { height: "6'1\"",  jersey: 86,  team: "New Jersey Devils",     position: "C",  conference: "Eastern", country: "USA",         age: 23 },
  "Nico Hischier":        { height: "6'2\"",  jersey: 13,  team: "New Jersey Devils",     position: "C",  conference: "Eastern", country: "Switzerland", age: 26 },
  "Jesper Bratt":         { height: "5'10\"", jersey: 63,  team: "New Jersey Devils",     position: "RW", conference: "Eastern", country: "Sweden",      age: 27 },
  "Dougie Hamilton":      { height: "6'6\"",  jersey: 7,   team: "New Jersey Devils",     position: "D",  conference: "Eastern", country: "Canada",      age: 32 },
  "Vitek Vanecek":        { height: "6'2\"",  jersey: 41,  team: "New Jersey Devils",     position: "G",  conference: "Eastern", country: "Czech Rep.",  age: 29 },
  "Tage Thompson":        { height: "6'7\"",  jersey: 72,  team: "Buffalo Sabres",        position: "C",  conference: "Eastern", country: "USA",         age: 27 },
  "Alex Tuch":            { height: "6'4\"",  jersey: 89,  team: "Buffalo Sabres",        position: "RW", conference: "Eastern", country: "USA",         age: 29 },
  "JJ Peterka":           { height: "6'0\"",  jersey: 77,  team: "Buffalo Sabres",        position: "RW", conference: "Eastern", country: "Germany",     age: 23 },
  "Devon Levi":           { height: "6'1\"",  jersey: 27,  team: "Buffalo Sabres",        position: "G",  conference: "Eastern", country: "Canada",      age: 23 },
  "Trevor Moore":         { height: "5'10\"", jersey: 12,  team: "Los Angeles Kings",     position: "RW", conference: "Western", country: "USA",         age: 30 },
  "Kevin Fiala":          { height: "5'10\"", jersey: 22,  team: "Los Angeles Kings",     position: "LW", conference: "Western", country: "Switzerland", age: 29 },
  "Phillip Danault":      { height: "6'1\"",  jersey: 24,  team: "Los Angeles Kings",     position: "C",  conference: "Western", country: "Canada",      age: 32 },
  "Vladimir Tarasenko":   { height: "6'0\"",  jersey: 91,  team: "Ottawa Senators",       position: "RW", conference: "Eastern", country: "Russia",      age: 33 },
  "Claude Giroux":        { height: "5'11\"", jersey: 28,  team: "Ottawa Senators",       position: "C",  conference: "Eastern", country: "Canada",      age: 37 },
  "Jakob Chychrun":       { height: "6'2\"",  jersey: 6,   team: "Ottawa Senators",       position: "D",  conference: "Eastern", country: "USA",         age: 27 },
  "Alexandar Georgiev":   { height: "6'1\"",  jersey: 40,  team: "Colorado Avalanche",    position: "G",  conference: "Western", country: "Bulgaria",    age: 29 },
  "MacKenzie Weegar":     { height: "6'0\"",  jersey: 52,  team: "Calgary Flames",        position: "D",  conference: "Western", country: "Canada",      age: 30 },
  "Andrew Mangiapane":    { height: "5'10\"", jersey: 88,  team: "Calgary Flames",        position: "LW", conference: "Western", country: "Canada",      age: 29 },
  "Jacob Markstrom":      { height: "6'6\"",  jersey: 25,  team: "Calgary Flames",        position: "G",  conference: "Western", country: "Sweden",      age: 35 },
  "Mikael Backlund":      { height: "6'1\"",  jersey: 11,  team: "Calgary Flames",        position: "C",  conference: "Western", country: "Sweden",      age: 36 },
  "Travis Konecny":       { height: "5'10\"", jersey: 11,  team: "Philadelphia Flyers",   position: "RW", conference: "Eastern", country: "Canada",      age: 28 },
  "Sean Couturier":       { height: "6'3\"",  jersey: 14,  team: "Philadelphia Flyers",   position: "C",  conference: "Eastern", country: "Canada",      age: 32 },
  "Ivan Provorov":        { height: "6'1\"",  jersey: 9,   team: "Columbus Blue Jackets", position: "D",  conference: "Eastern", country: "Russia",      age: 28 },
  "Bowen Byram":          { height: "6'1\"",  jersey: 4,   team: "Buffalo Sabres",        position: "D",  conference: "Eastern", country: "Canada",      age: 24 },
  "Mason McTavish":       { height: "6'2\"",  jersey: 23,  team: "Anaheim Ducks",         position: "C",  conference: "Western", country: "Canada",      age: 22 },
  "Trevor Zegras":        { height: "6'0\"",  jersey: 11,  team: "Anaheim Ducks",         position: "C",  conference: "Western", country: "USA",         age: 24 },
  "Troy Terry":           { height: "5'11\"", jersey: 19,  team: "Anaheim Ducks",         position: "RW", conference: "Western", country: "USA",         age: 27 },
  "John Gibson":          { height: "6'3\"",  jersey: 36,  team: "Anaheim Ducks",         position: "G",  conference: "Western", country: "USA",         age: 32 },
  "Alex Pietrangelo":     { height: "6'3\"",  jersey: 7,   team: "Vegas Golden Knights",  position: "D",  conference: "Western", country: "Canada",      age: 35 },
  "Jack Eichel":          { height: "6'2\"",  jersey: 9,   team: "Vegas Golden Knights",  position: "C",  conference: "Western", country: "USA",         age: 29 },
  "Jonathan Marchessault": { height: "5'9\"", jersey: 81,  team: "Vegas Golden Knights",  position: "LW", conference: "Western", country: "Canada",      age: 34 },
  "Adin Hill":            { height: "6'6\"",  jersey: 33,  team: "Vegas Golden Knights",  position: "G",  conference: "Western", country: "Canada",      age: 29 },
  "Mark Stone":           { height: "6'3\"",  jersey: 61,  team: "Vegas Golden Knights",  position: "RW", conference: "Western", country: "Canada",      age: 33 },
  "William Karlsson":     { height: "6'1\"",  jersey: 71,  team: "Vegas Golden Knights",  position: "C",  conference: "Western", country: "Sweden",      age: 32 },
  "Patrick Kane":         { height: "5'11\"", jersey: 88,  team: "Detroit Red Wings",     position: "RW", conference: "Eastern", country: "USA",         age: 37 },
  "Tyler Bertuzzi":       { height: "6'1\"",  jersey: 59,  team: "Toronto Maple Leafs",   position: "LW", conference: "Eastern", country: "Canada",      age: 30 },
  "William Nylander":     { height: "6'1\"",  jersey: 88,  team: "Toronto Maple Leafs",   position: "RW", conference: "Eastern", country: "Sweden",      age: 29 },
  "John Tavares":         { height: "6'1\"",  jersey: 91,  team: "Toronto Maple Leafs",   position: "C",  conference: "Eastern", country: "Canada",      age: 34 },
  "Morgan Rielly":        { height: "6'1\"",  jersey: 44,  team: "Toronto Maple Leafs",   position: "D",  conference: "Eastern", country: "Canada",      age: 31 },
  "Matt Murray":          { height: "6'4\"",  jersey: 30,  team: "Toronto Maple Leafs",   position: "G",  conference: "Eastern", country: "Canada",      age: 31 },
};
